// Generated by apps/server/scripts/update-llama-runtime.mjs — do not edit by hand.
// The one llama.cpp build this server will download, and the sha256 of every
// asset it may fetch. See the script for why this is pinned.

import type { RuntimeManifest } from "./runtime-types.ts";

export const RUNTIME_MANIFEST: RuntimeManifest = {
  "tag": "b11149",
  "commit": "d2e54583c7452353eb35d40431281f6ee984332f",
  "builds": {
    "darwin-arm64-metal": {
      "asset": {
        "name": "llama-b11149-bin-macos-arm64.tar.gz",
        "sha256": "791eb0200a7c846ca925b6274fc21f0f21f537fda2924cc5a47402655816f56e",
        "size": 11189509
      }
    },
    "darwin-arm64-cpu": {
      "asset": {
        "name": "llama-b11149-bin-macos-arm64.tar.gz",
        "sha256": "791eb0200a7c846ca925b6274fc21f0f21f537fda2924cc5a47402655816f56e",
        "size": 11189509
      }
    },
    "linux-x64-vulkan": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-vulkan-x64.tar.gz",
        "sha256": "d93606c124863e26750f0fa02daba8ae73aa39395507534fcbb57f5e7bbe7b55",
        "size": 30598088
      }
    },
    "linux-arm64-vulkan": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-vulkan-arm64.tar.gz",
        "sha256": "83ee53735830ab2650cbf71c931f4d038e5ea345c2c3c4a2350a1dc8abc646a5",
        "size": 24418109
      }
    },
    "linux-x64-cuda12": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-cuda-12.8-x64.tar.gz",
        "sha256": "c7dad8798b8aecfb1cf7dff2392979560c9e563facab51ee4df4e87a34acc92f",
        "size": 168929846
      }
    },
    "linux-x64-cuda13": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-cuda-13.4-x64.tar.gz",
        "sha256": "aea31810318a224026b723c154da1835ab5cca5e80a3834c72f644ac0e14750f",
        "size": 149275085
      }
    },
    "linux-arm64-cuda13": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-cuda-13.4-arm64.tar.gz",
        "sha256": "daa1441eb70434b00046902008090a02238a821f56f78c9cd065afaf7a71efe5",
        "size": 145036509
      }
    },
    "linux-x64-rocm": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-rocm-10.0-x64.tar.gz",
        "sha256": "8c5a1381376a8afd4690d6d6c2241368dcb5ccb69011733b28792bc3a26f6242",
        "size": 234721397
      }
    },
    "linux-x64-cpu": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-x64.tar.gz",
        "sha256": "214b9e26677221df9b6c84d396f236839c716a10acaf3eff8dde01fb26fbcd2c",
        "size": 16997871
      }
    },
    "linux-arm64-cpu": {
      "asset": {
        "name": "llama-b11149-bin-ubuntu-arm64.tar.gz",
        "sha256": "7a4ca8a91014a399dacb987efbd408621634e9079974f5a4fec80152d65b5e5b",
        "size": 13593527
      }
    },
    "win32-x64-vulkan": {
      "asset": {
        "name": "llama-b11149-bin-win-vulkan-x64.zip",
        "sha256": "ca432b775c5dcb5af85bbdcf22b06b6e2dca792f30334b19ef4a45ee4a512446",
        "size": 32126960
      }
    },
    "win32-x64-cuda12": {
      "asset": {
        "name": "llama-b11149-bin-win-cuda-12.4-x64.zip",
        "sha256": "d3140fe21ab2e665a706ca27923b27ca264f1c564b5837abea4566cc49c16096",
        "size": 253869752
      },
      "extra": {
        "name": "cudart-llama-bin-win-cuda-12.4-x64.zip",
        "sha256": "8c79a9b226de4b3cacfd1f83d24f962d0773be79f1e7b75c6af4ded7e32ae1d6",
        "size": 391443627
      }
    },
    "win32-x64-cuda13": {
      "asset": {
        "name": "llama-b11149-bin-win-cuda-13.4-x64.zip",
        "sha256": "24fa117fa4d34e24d121e13d7d1a542adbfc0fca24c96409e0824e9b5666072c",
        "size": 149758790
      },
      "extra": {
        "name": "cudart-llama-bin-win-cuda-13.4-x64.zip",
        "sha256": "738f8c251ac22b70c3ae6f83a10cf222725df0395246a2cf58f32bdb85fbe668",
        "size": 423535356
      }
    },
    "win32-x64-rocm": {
      "asset": {
        "name": "llama-b11149-bin-win-rocm-10.0-x64.zip",
        "sha256": "46a4eb51eb6ba6b677f67f1a4b37a82034560f484767915e6afaec43048c0ff0",
        "size": 251910635
      }
    },
    "win32-x64-cpu": {
      "asset": {
        "name": "llama-b11149-bin-win-cpu-x64.zip",
        "sha256": "d1cb5f9ef7bbb7068954b4c9767d5b5309e20bcefeb61d4aafc47f9581f38752",
        "size": 18559583
      }
    }
  }
};
