// Three apps out of one codebase: dev, beta, and production.
//
// `APP_VARIANT` decides which one is being built. Everything that makes them
// *different apps* rather than one app in three moods lives here — the display
// name, the bundle identifier and package name, the URL scheme, and the update
// channel the build follows — so dev, beta and production can sit side by side
// on one device, each updating from its own channel, with no switch inside the
// app to get wrong.
//
// Why a dynamic config at all: `ios/` and `android/` are generated by prebuild
// and gitignored, so identity cannot be edited into them by hand — it has to
// come from config every time they are regenerated.
//
// Why `app.json` survives next to it: Expo loads the JSON first and hands it
// here as `config`, and `apps/desktop/scripts/stamp-version.mjs` writes the
// release version into that file by parsing and re-serialising it. A single
// dynamic config would leave the stamp nothing to write to. So the JSON holds
// everything identical across variants, and this file overlays the rest —
// `version` included, untouched, which is the contract the stamp relies on.
//
// The channel is embedded in the build rather than chosen at runtime. The
// runtime override that `expo-updates` offers persists natively across
// launches, which makes "which channel is this install on?" a question with
// two possible answers; a build that can only be one thing has one.

/**
 * Where the public half of the update-signing key pair lives, and how a
 * manifest signed with the private half is labelled.
 *
 * A build that carries this certificate accepts an update only if the manifest
 * arrives with a signature the certificate verifies. Without it, expo-updates
 * trusts whatever the update server returns — so the EAS account would be the
 * only thing standing between a leaked `EXPO_TOKEN` and arbitrary JavaScript
 * in every install. With it, publishing an update people's phones will run
 * takes the private key as well, and that key has never been in this
 * repository, in EAS, or in an EXPO_TOKEN's reach.
 *
 * The path is relative to this directory and resolved twice, by two different
 * things, which is why it can be one string: `@expo/config-plugins` joins it
 * to the project root at prebuild and embeds the file's *contents* in
 * Expo.plist / strings.xml, and `eas update` reads it from the working
 * directory to check the private key it was given actually matches.
 *
 * `keyid` is a label carried in the signature, not a secret and not a lookup —
 * it exists so a future second key can be told apart from this one. `alg` is
 * the only algorithm expo-updates implements.
 */
const CODE_SIGNING = {
  certificate: "./certs/certificate.pem",
  metadata: { keyid: "main", alg: "rsa-v1_5-sha256" },
};

const VARIANTS = {
  production: {
    name: "Loxaic",
    // No suffix: production keeps the identifiers any existing build already
    // has, so it is the variant that can be published to a store.
    suffix: "",
    scheme: "loxaic",
    channel: "production",
    signed: true,
  },
  beta: {
    name: "Loxaic Beta",
    suffix: ".beta",
    scheme: "loxaic-beta",
    channel: "beta",
    signed: true,
  },
  dev: {
    // Deliberately unsigned, and it is the one variant that can be.
    //
    // Signing costs the publisher the private key at publish time, and the dev
    // channel publishes on every merge to the trunk — so its key would have to
    // be a repository secret, readable by a workflow on any branch. That is
    // the same blast radius as EXPO_TOKEN, which would leave beta and
    // production defended by a key sitting next to the thing it defends
    // against. Keeping dev out lets the real key live as an environment secret
    // that only a tag release can reach.
    //
    // What that costs: the dev channel has no integrity check at all. The dev
    // app is the owner's own build, pointed at the owner's own stack, and is
    // not distributed — which is the reason this trade is acceptable here and
    // would not be for an app anybody else installs.
    name: "Loxaic Dev",
    suffix: ".dev",
    scheme: "loxaic-dev",
    channel: "dev",
    signed: false,
  },
};

/**
 * Unset means production — the plain `expo start` / Expo Go / `expo export`
 * path a contributor takes without knowing this file exists. An *unrecognised*
 * value throws instead: a typo in a build profile must not quietly produce a
 * production build under a name nobody meant to ship.
 *
 * An empty string throws too, deliberately, even though it is what a declared
 * but unset CI variable expands to. Treating it as production would be the
 * friendlier default and the wrong one: the channel the binary embeds comes
 * from here while the channel CI publishes to comes from the `--channel` flag,
 * so a variable that failed to expand would produce a build embedded with
 * `production` and an update published to `beta` — one that reaches nobody,
 * with no error anywhere. Failing the build is the louder half of that choice.
 */
function variantFor(raw) {
  const key = raw ?? "production";
  // `Object.hasOwn`, not `VARIANTS[key]`: a plain lookup walks the prototype
  // chain, so APP_VARIANT=constructor (or toString, or valueOf) found a
  // function instead of a variant and sailed past the throw below — producing
  // an app named `undefined` with the identifier `com.loxaic.appundefined`,
  // no scheme, and no `expo-channel-name` header at all, which is a build that
  // follows no channel and silently receives no updates for its whole life.
  const variant = Object.hasOwn(VARIANTS, key) ? VARIANTS[key] : undefined;
  if (!variant) {
    throw new Error(
      `APP_VARIANT="${key}" is not one of ${Object.keys(VARIANTS).join(", ")}`,
    );
  }
  return { key, ...variant };
}

module.exports = ({ config }) => {
  const variant = variantFor(process.env.APP_VARIANT);
  return {
    ...config,
    name: variant.name,
    // `slug` deliberately does not vary: it identifies the EAS project that
    // all three variants publish updates through, and changing it per variant
    // would mean three projects and three sets of credentials.
    scheme: variant.scheme,
    // Derived from what app.json declares rather than repeating the base
    // identifier here. Hard-coding it made app.json's copy dead: it is the
    // file that looks like the source of truth for identity, and renaming the
    // app there would have changed nothing while prebuild quietly kept
    // regenerating the old identifier from this file.
    ios: {
      ...config.ios,
      bundleIdentifier: `${config.ios.bundleIdentifier}${variant.suffix}`,
    },
    android: { ...config.android, package: `${config.android.package}${variant.suffix}` },
    updates: {
      ...config.updates,
      // expo-updates only honours a channel the build already embeds, and this
      // is where it gets embedded. It is also what the matching `eas update`
      // has to publish to — a build and an update that disagree here produce
      // an update nobody receives.
      requestHeaders: { "expo-channel-name": variant.channel },
      // Spread, not two `undefined`s: `eas update` decides whether an update
      // must be signed by asking whether the resolved config has a
      // `codeSigningCertificate` at all, so a key left in place holding
      // `undefined` would make an unsigned variant refuse to publish without
      // `--private-key-path`. It has to carry no key.
      ...(variant.signed
        ? {
            codeSigningCertificate: CODE_SIGNING.certificate,
            codeSigningMetadata: CODE_SIGNING.metadata,
          }
        : {}),
    },
    extra: { ...config.extra, variant: variant.key },
  };
};

// Exported for the test, which is the only thing that needs the table itself,
// and for fingerprint.config.js, which has to answer the same question this
// file does — whether this variant embeds the certificate — from one table
// rather than two that can drift.
module.exports.VARIANTS = VARIANTS;
module.exports.CODE_SIGNING = CODE_SIGNING;
module.exports.variantFor = variantFor;
