// Three apps out of one codebase: dev, beta, and production.
//
// `APP_VARIANT` decides which one is being built. Everything that makes them
// *different apps* rather than one app in three moods lives here — the display
// name, the bundle identifier and package name, the URL scheme, and the update
// channel the build follows — so dev, beta and production can sit side by side
// on one device, each updating from its own channel, with no switch inside the
// app to get wrong.
//
// Why a dynamic config at all: `ios/` and `android/` are generated by prebuild
// and gitignored, so identity cannot be edited into them by hand — it has to
// come from config every time they are regenerated.
//
// Why `app.json` survives next to it: Expo loads the JSON first and hands it
// here as `config`, and `apps/desktop/scripts/stamp-version.mjs` writes the
// release version into that file by parsing and re-serialising it. A single
// dynamic config would leave the stamp nothing to write to. So the JSON holds
// everything identical across variants, and this file overlays the rest —
// `version` included, untouched, which is the contract the stamp relies on.
//
// The channel is embedded in the build rather than chosen at runtime. The
// runtime override that `expo-updates` offers persists natively across
// launches, which makes "which channel is this install on?" a question with
// two possible answers; a build that can only be one thing has one.

const VARIANTS = {
  production: {
    name: "Loxaic",
    // No suffix: production keeps the identifiers any existing build already
    // has, so it is the variant that can be published to a store.
    suffix: "",
    scheme: "loxaic",
    channel: "production",
  },
  beta: {
    name: "Loxaic Beta",
    suffix: ".beta",
    scheme: "loxaic-beta",
    channel: "beta",
  },
  dev: {
    name: "Loxaic Dev",
    suffix: ".dev",
    scheme: "loxaic-dev",
    channel: "dev",
  },
};

/**
 * Unset means production — the plain `expo start` / Expo Go / `expo export`
 * path a contributor takes without knowing this file exists. An *unrecognised*
 * value throws instead: a typo in a build profile must not quietly produce a
 * production build under a name nobody meant to ship.
 */
function variantFor(raw) {
  const key = raw ?? "production";
  const variant = VARIANTS[key];
  if (!variant) {
    throw new Error(
      `APP_VARIANT="${key}" is not one of ${Object.keys(VARIANTS).join(", ")}`,
    );
  }
  return { key, ...variant };
}

module.exports = ({ config }) => {
  const variant = variantFor(process.env.APP_VARIANT);
  return {
    ...config,
    name: variant.name,
    // `slug` deliberately does not vary: it identifies the EAS project that
    // all three variants publish updates through, and changing it per variant
    // would mean three projects and three sets of credentials.
    scheme: variant.scheme,
    ios: { ...config.ios, bundleIdentifier: `com.loxaic.app${variant.suffix}` },
    android: { ...config.android, package: `com.loxaic.app${variant.suffix}` },
    updates: {
      ...config.updates,
      // expo-updates only honours a channel the build already embeds, and this
      // is where it gets embedded. It is also what the matching `eas update`
      // has to publish to — a build and an update that disagree here produce
      // an update nobody receives.
      requestHeaders: { "expo-channel-name": variant.channel },
    },
    extra: { ...config.extra, variant: variant.key },
  };
};

// Exported for the test, which is the only thing that needs the table itself.
module.exports.VARIANTS = VARIANTS;
